---

- name: Configuring module
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - "etc/php5/mods-available/newrelic.ini"
